configure: preserve CUDA link errors for the user

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1059,7 +1059,7 @@ fi
 #
 # CUDA/nvcc setup
 # TODO: error reporting could be improved substantially.
-# In particular, we discard (nearly?) all failure output from nvcc
+# In particular, we discard much of the failure output from nvcc
 #
 if [[ $UPCXX_CUDA -eq 1 ]]; then
   # PREpend to allow user to disable if needed
@@ -1166,18 +1166,29 @@ if [[ $UPCXX_CUDA -eq 1 ]]; then
   fi
 
   # check that the CUDA Driver API is linkable, adding explicit link flags if needed
+  DETAIL_LOG=config-cuda.log
+  rm -f $DETAIL_LOG
   echo -e "#include <cuda.h>\n#include <cuda_runtime_api.h>\nint main() { cuInit(0); return 0; }" >| conftest.cpp
   for ldextra in '' '-lcuda' '-framework CUDA' 'FAIL'; do
-    eval $CXX $UPCXX_CUDA_CPPFLAGS $LDFLAGS conftest.cpp -o conftest.exe $UPCXX_CUDA_LIBFLAGS $ldextra &> /dev/null
-    if [[ $? -eq 0 ]] && ( ./conftest.exe 2>/dev/null ); then
-      [[ -n "$ldextra" ]] && UPCXX_CUDA_LIBFLAGS+=" $ldextra"
-      break
+  (
+    cmd="$CXX $UPCXX_CUDA_CPPFLAGS $LDFLAGS conftest.cpp -o conftest.exe $UPCXX_CUDA_LIBFLAGS $ldextra"
+    echo '$' $cmd
+    eval $cmd
+    if [[ $? -eq 0 ]]; then
+      echo '$ ./conftest.exe'
+      if ./conftest.exe; then
+        [[ -n "$ldextra" ]] && UPCXX_CUDA_LIBFLAGS+=" $ldextra"
+        break
+      fi
     fi
+  ) &>> $DETAIL_LOG
   done
   rm -f conftest.cpp conftest.exe
   if [[ "$ldextra" == 'FAIL' ]]; then
-    echo_and_die 'failed to link against CUDA Driver API'
+    echo_and_die "failed to link against CUDA Driver API.  See $DETAIL_LOG for the link commands attempted and their output."
   fi
+  rm -f $DETAIL_LOG
+  unset DETAIL_LOG
   trap failure_and_die ERR  # restore error handler
 
   [[ -z ${CUDA_LIBS} ]] && CUDA_LIBS=${UPCXX_CUDA_LIBFLAGS}
